export const DELATE_CITY = 'CITY/DELATE_CITY'
export const ADD_CITY = 'CITY/ADD_CITY'
export const ADD_ERROR_MESSAGE = 'CITY/ADD_ERROR_MESSAGE'
export const CLEAR_ERROR_MESSAGE = 'CITY/CLEAR_ERROR_MESSAGE'